### ISSUE TITLE
The New Call of Duty - Online Patch makes the Patch not Usuable. Will it be Updated?

### ISSUE THREAD

**Issue by TohruAdachi255** [dtzxporter/ProjectD3code#1]
It really Helped alot.

**Comment by dtzxporter** [comment]
I've just released the last update I'll ever be releasing.

**Comment by TohruAdachi255** [comment]
Thank you Bro! I Really Appreciate You!

**Comment by TohruAdachi255** [comment]
But why is it gonna be the Last Update? Too many People Bugging you? If you don’t wanna Update it no more can I take on your Mantle?
